name: CI

on:         
  push:
    branches: [ "main" ]  
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

        #Клонирую репозиторий в runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

        # Подключаю лкружение компилятора Microsoft Visual C++
      - name: Setup MSVC environment (Windows only)
        if: matrix.os == 'windows-latest'
        uses: ilammy/msvc-dev-cmd@v1

        #Запуск конфигурации CMake
      - name: Configure with CMake (Windows)
        if: matrix.os == 'windows-latest'
        run: cmake -B build 
        shell: cmd
        
      - name: Configure with CMake (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: cmake -B build
        shell: bash

        #Сборка
      - name: Build with CMake (Windows)
        if: matrix.os == 'windows-latest'
        run: cmake --build build --config Release
        shell: cmd

      - name: Build with CMake (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: cmake --build build --config Release
        shell: bash

        #Загрузка артефактов на GitHub
      - name: Upload release artifacts (Windows)
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: windows-Sortirovka-release
          path: build\Release\
          retention-days: 7

      - name: find file
        if: matrix.os == 'ubuntu-latest'
        run: find . -maxdepth 2 -executable -type f
        shell: bash

      - name: Upload release artifacts (Linux)
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: linux-Sortirovka-release
          path: build/Release
          retention-days: 7